In [2]:
import numpy as np
uniform=np.random.rand(3,3)
print("uniform Distribution",uniform)

uniform Distribution [[0.6932225  0.81600326 0.56190765]
 [0.43632735 0.12959328 0.3409946 ]
 [0.10489511 0.8461078  0.4720311 ]]


In [3]:
arr=np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [4]:
print("Where > 3:", np.where(arr > 3))

Where > 3: (array([3, 4], dtype=int64),)


In [5]:
np.argmax(arr)

4

In [6]:
sorted_arr=np.array([1,3,5,7])
np.searchsorted(sorted_arr,6)

3

In [7]:
arr=np.array([1,2,3,4,5])
np.extract(arr>3,arr)

array([4, 5])

In [8]:
matrix=np.array([[1,2,3],[4,5,6]])
print("Original:\n",matrix)

Original:
 [[1 2 3]
 [4 5 6]]


In [9]:
print("Transposed :\n",np.transpose(matrix))

Transposed :
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
#Mean Calculation
arr=np.array([1,2,3,4,5])
print("mean value: ",np.mean(arr))

mean value:  3.0


In [11]:
arr=np.array([1, 2, 3, 4, 5, 6])
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [12]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
np.split(matrix,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [13]:
np.split(matrix,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [14]:
arr=np.array([2,7,1,4,5])
print("Sorted copy :" ,np.sort(arr))

Sorted copy : [1 2 4 5 7]


In [15]:
matrix=np.array([[3,1,7],
                 [6,5,4]])
print("sorted Rows:\n", np.sort(matrix,axis=1))

sorted Rows:
 [[1 3 7]
 [4 5 6]]
